### ISSUE TITLE
no gui, boots to shell

### ISSUE THREAD

**Issue by patkub** [patkub/antuple-fedora#7]
TODO: setup gui

**Comment by axk4545** [comment]
This can be fixed by %including any of 
f

- edora-live-cinnamon.ks
- fedora-live-kde.ks
- fedora-live-lxde.ks
- fedora-live-mate_compiz.ks
- fedora-live-soas.ks
- fedora-live-workstation.ks
- fedora-live-xfce.ks

**Comment by patkub** [comment]
Is fedora-live-workstation.ks all I need for the live image found here?https://getfedora.org/en/workstation/download/
