### ISSUE TITLE
Build process time

### ISSUE THREAD

**Issue by patkub** [patkub/antuple-fedora#8]
Disable verification for test builds to speed-up

**Comment by patkub** [comment]
[virt-install-v1.txt](https://github.com/patkub/antuple-fedora/files/812997/virt-install-v1.txt)

**Comment by patkub** [comment]
https://marcin.juszkiewicz.com.pl/2016/04/15/how-to-speed-up-mock/

**Comment by patkub** [comment]
1 hr 50 min after speed up

[virt-install.txt](https://github.com/patkub/antuple-fedora/files/813530/virt-install.txt)

**Comment by axk4545** [comment]
@patkub I found your issue. in the iso generation part of your script, you run a vm in mock. add the --no-virt option to fix it

**Comment by axk4545** [comment]
@patkub I found your issue. your build script runs a vm in mock when building the iso. add the --no-virt option to fix it.

**Comment by patkub** [comment]
So I pretty much had a vm inside a vm, no wonder its so slow. Thx

**Comment by axk4545** [comment]
:)
